version: '3.9'
services:
  server:
    build: server
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .config/db.env
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .config/db.env
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  node_modules:
